# Generated by Django 5.1.7 on 2025-03-12 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_lendings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklending',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booklending',
            name='returned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
