# Generated by Django 5.1.7 on 2025-03-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_lendings', '0002_alter_booklending_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklending',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
